### ISSUE TITLE
Support watching .mjs (javascript module) files

### ISSUE THREAD

**Issue by shofetim** [porsager/wright#42] opened 2020-03-03 17:10 UTC
It looks like wright only watches .js .ts and .ls files. Most of my client side JS is in .mjs files these days, served without a build process (it is a little cutting edge, but browser support is good, and I don't need to support every browser).

**Comment by porsager** [comment] 2020-09-28 14:16
Hi. Sorry for the late reply.

I haven't taken mjs into consideration since mjs has no meaning in the browser, and is purely a node construct. I think the verdict is still out on mjs generally, so I'm not seeing myself looking into it, but if you want to PR support yourself, I'm fine with that 🙂

**Comment by porsager** [comment] 2020-09-28 14:20
Apparently I did have a [weird condition regarding mjs](https://github.com/porsager/wright/commit/d21e86d82ac15a1a476ec49c2ef10f0af854a021) that seemed to be reversed, and probably the cause for watching not working, so I've gone ahead and fixed that 😛 Let me know if it does anything for you.

**Comment by shofetim** [comment] 2020-09-28 14:21
Thank you for the response, late or no.

You type faster than I do. The below might still be of some use though.

I guess the _file extension_ .mjs likely has no meaning to browsers, they use the `<script type="module">` instead, but browsers _do_ widely support [ES6 modules](https://caniuse.com/es6-module) - no need for transpiling/node/etc.

**Comment by porsager** [comment] 2020-09-28 14:24
> I guess the file extension .mjs likely has no meaning to browsers, they use the <script type="module"> instead, but browsers do widely support ES6 modules - no need for transpiling/node/etc.

Oh definitely.. I run all my projects with wright 2.0 without transpiling using `type="module"`.

**Comment by porsager** [comment] 2021-01-08 22:41
I think this should be fixed with the latest release.

**Closed as completed by porsager** 2021-01-08 22:41 UTC
